version: "3.9"
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: appdb
    ports: ["5432:5432"]
    volumes: ["pgdata:/var/lib/postgresql/data"]
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build: .
    depends_on:
      db:
        condition: service_healthy
    env_file: .env
    ports: ["8000:8000"]
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000

  locust:
    image: locustio/locust:latest
    depends_on: [ app ]
    environment:
      LOCUST_HOST: http://app:8000
    ports: ["8089:8089"]
    volumes: [ "./scripts/loadtest:/mnt/locust" ]
    command: -f /mnt/locust/locustfile.py

volumes:
  pgdata:
