name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Copy env example
        run: cp .env.example .env

      - name: Build images
        run: docker compose build

      - name: Start database
        run: docker compose up -d db

      - name: Wait for db
        run: |
          for i in {1..60}; do
            if docker compose exec -T db pg_isready -U postgres >/dev/null 2>&1; then
              echo "DB is ready"; exit 0
            fi
            echo "Waiting for db..."
            sleep 2
          done
          echo "DB not ready in time" >&2
          docker compose logs --no-color db
          exit 1

      - name: Run tests (compose run)
        run: docker compose run --rm app pytest -q

      - name: Print logs on failure
        if: failure()
        run: |
          docker compose ps
          docker compose logs --no-color db app || true

      - name: Stop services
        if: always()
        run: docker compose down -v
