name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Copy env example
        run: cp .env.example .env

      - name: Build & start services
        run: |
          docker compose up --build -d
          for i in {1..30}; do
            curl -fsS http://localhost:8000/ && break
            echo "Waiting for app to be ready..."
            sleep 2
          done

      - name: Run tests (inside app container)
        run: docker compose exec -T app pytest -q

      - name: Stop services
        if: always()
        run: docker compose down -v
